WebApplication11/Models/ProductModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication11.Models
{
    public class ProductModel
    {
        [Key]
        public int Id { get; set; }
        public string ProductName { get; set; }
        public decimal ProductPrice { get; set; }
       
        public string ProfilePicture { get; set; }

        public string Description { get; set; }

        //public IFormFile ProfilePicture { get; set; }

    }
}

WebApplication11/Controllers/ProductModelsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication11.Data;
using WebApplication11.Models;

namespace WebApplication11.Controllers
{
    [Authorize]
    public class ProductModelsController : Controller

    {
        // int Count = 0;

        private readonly DatabaseContaxt _context;
        private readonly IWebHostEnvironment webHostEnvironment;
        public ProductModelsController(DatabaseContaxt context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;

            webHostEnvironment = hostEnvironment;

        }

        // GET: ProductModels
        public async Task<IActionResult> Index()
        {
            return View(await _context.ProductModels.ToListAsync());
        }

        // GET: ProductModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productModel = await _context.ProductModels
                .FirstOrDefaultAsync(m => m.Id == id);
            if (productModel == null)
            {
                return NotFound();
            }

            return View(productModel);
        }



        // GET: ProductModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productModel = await _context.ProductModels.FindAsync(id);
            if (productModel == null)
            {
                return NotFound();
            }
            return View(productModel);
        }

        // POST: ProductModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProductName,ProductPrice,ProfilePicture")] ProductModel productModel)
        {
            if (id != productModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(productModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductModelExists(productModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(productModel);
        }

        // GET: ProductModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productModel = await _context.ProductModels
                .FirstOrDefaultAsync(m => m.Id == id);
            if (productModel == null)
            {
                return NotFound();
            }

            return View(productModel);
        }

        // POST: ProductModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var productModel = await _context.ProductModels.FindAsync(id);
            _context.ProductModels.Remove(productModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductModelExists(int id)
        {
            return _context.ProductModels.Any(e => e.Id == id);
        }


        [HttpPost]
        public IActionResult DetailsSending(int id)
        {

            var obj = new CartData()
            {
                ProductId = id,
                UserId = "123"
            };
            if (obj != null)
            {
                _context.Carts.Add(obj);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }


        public async Task<IActionResult> getcartItems(int id)
        {
            var person = new List<ProductModel>();

            person = await (from pro in _context.ProductModels
                            join cd in _context.Carts on pro.Id equals cd.ProductId
                            where pro.Id == id
                            select pro).ToListAsync();
            return View(person);
        }

        //private string ProcessUploadedFile(ProductModel model)
        //{
        //    string uniqueFileName = null;

        //    if (model.ProfilePicture != null)
        //    {
        //        string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "Uploads");
        //        uniqueFileName = Guid.NewGuid().ToString() + "_" + model.ProfilePicture.FileName;
        //        string filePath = Path.Combine(uploadsFolder, uniqueFileName);
        //        using (var fileStream = new FileStream(filePath, FileMode.Create))
        //        {
        //            model.ProfilePicture.CopyTo(fileStream);
        //        }
        //    }

        //    return uniqueFileName;
        //}


    }
}

WebApplication11/Views/ProductModels/Delete.cshtml
@model WebApplication11.Models.ProductModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProductModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProfilePicture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProfilePicture)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplication11/Views/ProductModels/Details.cshtml
@model WebApplication11.Models.ProductModel

@{
    ViewData["Title"] = "Details";
}
<form  asp-controller="ProductModels" asp-action="DetailsSending" asp-route-id="@Model.Id" >
    <a class="justify-content-end btn border border-gray border-3" asp-controller="ProductModels" asp-action="getcartItems" asp-route-id="@Model.Id">
        <i class="bi bi-cart3"></i>
        Cart
    </a>


    <div class="container-fluid ">
        <div class="row justify-content-center">
            <div class="col-sm-6">


                <H1 class="text-white text-center mt-5 mb-3">@Html.DisplayFor(model => model.ProductName)</H1>
                <div class="row img-fluid">
                    <img src="@Url.Content("~/Uploads/" +Model.ProfilePicture)" alt="Error" />

                </div>


            </div>

            <div class="col-sm-5 bg-dark mt-5 p-5 border border-3 border-light rounded h-50 ">
                <ul class="list-unstyled">
                    <li>
                        <div class="row text-success fw-bold fs-3 mt-5 mb-2">
                            <i class="bi bi-check-circle">
                                In Stock
                            </i>

                        </div>

                    </li>
                    <li>
                        <div class="fs-5 ms-4 mt-2 mb-2 ">
                            <strong>@Html.DisplayFor(modelItem => Model.Description)</strong>

                        </div>
                    </li>
                    <li>
                        <div class="col-sm-12 fw-bold fs-5">
                            <i class="bi bi-truck me-2"></i>
                            FREE delivery to you
                            <i class="text-info bi bi-info-circle-fill"></i>
                        </div>
                    </li>
                    <li>
                        <div class="text-center text-info  display-4  fw-bold mt-5 mb-3">
                            $@Html.DisplayFor(modelItem => Model.ProductPrice)
                            @*<input asp-for="Id" class="form-control" />*@

                        </div>
                    </li>
                    <li>


                        <div class=" row justify-content-center">
                            @Html.HiddenFor(modelItem => Model.Id)
                            <input class="btn border border-3 border-seccess"
                            type="submit" value="Add to Cart" 
                            />

                        </div>
                    </li>

                </ul>

            </div>

        </div>

    </div>

</form>

WebApplication11/Views/ProductModels/Edit.cshtml
@model WebApplication11.Models.ProductModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ProductModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductPrice" class="control-label"></label>
                <input asp-for="ProductPrice" class="form-control" />
                <span asp-validation-for="ProductPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProfilePicture" class="control-label"></label>
                <input asp-for="ProfilePicture" class="form-control" />
                <span asp-validation-for="ProfilePicture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication11/Views/ProductModels/Index.cshtml
@model IEnumerable<WebApplication11.Models.ProductModel>
@{
    ViewData["Title"] = "Index";
}

<h1 class="text-light bg-dark text-center">Product Screen</h1>
<div class="container">
    <div class="row mt-10 justify-content-center">
        @foreach (var item in Model)
        {
            <div class="col-sm-4">
                <div class="row justify-content-center text-light fs-3 m-3 fw-bold badge bg-Dark">
                    @Html.DisplayFor(modelItem => item.ProductName)

                </div>
                <div class="row justify-content-center pb-2">
                    <img src="@Url.Content("~/Uploads/" +item.ProfilePicture)" alt="Error" class="img-fluid">

                </div>
                <hr>
                <div class="row justify-content-center display-7 m-7">
                    <strong class="text-center">
                        From
                        <br>
                        $@Html.DisplayFor(modelItem => item.ProductPrice)
                        <br>
                        Per Month
                    </strong>

                </div>
                <div>
                    <div class="row justify-content-center">
                        <a class="col-sm-10 btn btn-primary"
                       asp-controller="ProductModels"
                       asp-action="Details"
                       asp-route-id="@item.Id">Details</a>
                    </div>

                </div>

            </div>

        }

    </div>

</div>

@*             <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>*@

WebApplication11/Views/ProductModels/getcartItems.cshtml
@model IEnumerable<WebApplication11.Models.ProductModel>

@{
    ViewData["Title"] = "Cart";
}

<table class="p-3">
    @foreach (var item in Model)
    {
        <tbody class=" m-5 p-3">
            <tr>
                <td class="col-sm-3">
                    <img src="@Url.Content("~/Uploads/" +item.ProfilePicture)" class="img-fluid w-25" alt="Error" />
                </td>
                <td class="col-sm-5">
                    <div class="fs-3 me-5">
                        @Html.DisplayFor(modelItem => item.ProductName)
                    </div>
                </td>
                <td class="col-sm-4 fs-2">

                    $@Html.DisplayFor(modelItem => item.ProductPrice)
                <td>
            </tr>
          
        </tbody>





        @*  <td>
            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>*@

    }
</table>